### PR TITLE
note that you need to restart after addgroup

### PR DESCRIPTION
**Pull request by 534o**

### CODE REVIEW

**Comment by 534o** [comment]
@7675t can you run bloom-release for this package?

**Comment by 7675t** [comment]
Pre-release test has just finished.
I'm bloom-releasing for Indigo and Kinetic.

**Comment by 7675t** [comment]
I got some error, maybe I should get the release repo public.

**Comment by 7675t** [comment]
I think I've done.

https://github.com/ros/rosdistro/pull/16797
https://github.com/ros/rosdistro/pull/16798

kinetic's failed in test, because the release repo was private...  Can we just wait for the next build?

**Comment by 7675t** [comment]
They are merged.

https://github.com/ros/rosdistro/pull/16798
https://github.com/ros/rosdistro/pull/16797

**Pull request merged**
