### PR TITLE
Add bias estimation service

### PR DESCRIPTION
**Pull request by 7675t**
- Add bias_estimate service for ADIS16470

### CODE REVIEW

**Comment by 534o** [comment]
debug in circleci is not as difficult as travis, try ssh https://qiita.com/tsuka611/items/21cb29c49883e41de1c8

i could not find automatic migration tool so far, so need to upgrade manually 
https://qiita.com/kaorupochi/items/46d45b49953f61340518

**Comment by 534o** [comment]
run deploy job only for tagged commit is tricky, see 
https://github.com/tork-a/cheatsheet/blob/master/.circleci/config.yml

**Comment by 7675t** [comment]
I have learned how can I setup with CircleCI 2.0, here https://github.com/tork-a/adi_driver/pull/16
But should we keep this CI for this package? Pdf and deb were for delivery and it is already done well. I think we can remove it after releasing this package.

**Comment by 534o** [comment]
we do not need to build deb, but I think building pdf is still important, or switch to readthedocs or rosdoc or something else.

**Pull request merged**
