### PR TITLE
Add ADIS16495-2 driver.

### PR DESCRIPTION
**Pull request by jonny214**
Hello,

I add the driver code for ADIS16495-2.
Please review the code. And, if possible, please update the code.

USB-ISS is under 100mA current. ADIS16495 need over 100mA.
So, I add LDO(5V to 3.3V Linear regulator) and jumper connection for supplying current for ADIS16495-2.

Best regards,
Jun

### CODE REVIEW

**Comment by 7675t** [comment]
@jonny214 Thank you for your PR. Let me see it for a while.

**Comment by 7675t** [comment]
@jonny214 Can you rebase your PR onto current master?
Some change have been made before your PR.

Assuming you have following git repository, 
```
$ git remte -v
jonny214	https://github.com/jonny214/adi_driver.git (fetch)
jonny214	https://github.com/jonny214/adi_driver.git (push)
origin	https://github.com/tork-a/adi_driver.git (fetch)
origin	https://github.com/tork-a/adi_driver.git (push)
```

You can rebase your change as:
```
$ git checkout master
$ git pull origin master
$ git checkout adis16495
$ git rebase master
```

You should have no errors. Then,

```
$ git push jonny214 adis16495
```

will update your PR.
If you are not clear, please consult git documents or just ask me.

**Comment by jonny214** [comment]
Hi,

Thank you so much!

I tried to "rebase" for the pull request.
The last command did,

`$ git push origin adis16495`

There was no error on all the process.
Did it update the git repository? 
If I need new pull request or another action, please let me know.

Best regards,
Jun

**Comment by 7675t** [comment]
Sorry, my comment was not correct. When you try to push, you should get error like:

```
$ git push origin adis16495 
To https://github.com/jonny214/adi_driver.git
 ! [rejected]        adis16495 -> adis16495 (non-fast-forward)
error: failed to push some refs to 'https://github.com/jonny214/adi_driver.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

If you don't see this error, your branch is not rebased to master. Please check your branch is successfully rebased. `git log` should show 1.0.3 tag before your commits. 

And to prevent the error to push, you need force option like:

```
$ git push -f origin adis16495
```

**Comment by jonny214** [comment]
Hi,

My local repository could not update from the latest code.
So, i will re-try to make new repository and pull request to this.

Sorry for confusion.

Best regards,
Jun

**Pull request closed without merging**
